# Generated by Django 3.1.6 on 2021-02-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product', max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, help_text='eg. 19.99', max_digits=10)),
                ('description', models.TextField(help_text='Products Description')),
                ('new', models.BooleanField(default=True)),
                ('best_seller', models.BooleanField(default=False)),
            ],
        ),
    ]
